language: python
python:
- '3.5'
- '3.6'
install:
- pip3 install -r requirements.txt
- pip3 install coveralls
script: nosetests -w minghu6_test --with-coverage --cover-package=minghu6
sudo: false
after_success:
  coveralls
deploy:
  provider: pypi
  user: minghu6
  password:
    secure: D0UFYDtbJz2ByOhcAFLbFZTqtWMXZp9myZZy/y2+gN2aRHVK6beRScMKltPV7if1S8TsTs7uFICMeBGARKuEuTwB0WBFdnk9x4QMJTfu2msaETXbUa9caJZ0Cd5IlHgtkgTClexeSO0cPl2CgU2shUSga3vJlgch6YE2Af/A/fk4xcBCH11+3KX4gR5awk7JDneW5twRRgH3lTak/8LbnSQsVHLanNNwdvfABKb1bV90lA0gWBnQIzG0irU/ut1OUBEEmOx3FNBawvmVcVc8ToJrrWLHZ72qxByAO94Ms1kTdmdikI/4Uq87cMpPHephufqQmkA1P3Lb3bojIIq0NdozmSxyl7ix5B3uOWELw/p/B65AwqIyJJeNRxEKl03dS4HOvlihh8Ssh0g96dNM3uyldGZe+qOofxsN5qOQJRP+WJTioRZzRZ0tw/RugL7HfGN1jcjGh0OgX2KDDC8gEUlsKPD/7FTil2dM0tVKTWB2qIZ8SzhYqtZ2M2tGF57eLrHOEhFNf+d6rVD6JsJZrXQJ8BOPKWRvCHwveA60I2hHWw08X2ery7CbUkYk3dMx56JOerEMcaPTZ85m3GLoT2M4nKjS73ZytcJ/1AVTREjis6le7N6D9xtwLcZhtr68MdhxOYuxL7fyUfp19OwjVV/tjGk/HD7NNBIL04Qhtw0=
  on:
    tags: true
    repo: minghu6/minghu6_py
    all_branches: true
